# Generated by Django 2.2.9 on 2023-11-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Наименование тэгов',
                'verbose_name_plural': 'Наименование тэгов',
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Основной')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scopes', to='articles.Article')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scopes', to='articles.Tag')),
            ],
            options={
                'verbose_name': 'Связки тэгов',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Tag'),
        ),
    ]
