# Generated by Django 2.2.9 on 2023-11-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20231111_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopes',
            old_name='name',
            new_name='tag',
        ),
    ]
