# Generated by Django 2.2.9 on 2023-11-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20231111_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopes',
            old_name='tag',
            new_name='name',
        ),
    ]
